### ISSUE TITLE
Contributing: what to use for minification and tests?

### ISSUE THREAD

**Issue by leocavalcante** [luisvinicius167/gliojs#3]
Hi @luisvinicius167,

I'm willing to contribute on the project, but what do you use now to minify? Have you already thought about using GulpJS or GruntJS to automate this process?

And have you thought about a testing framework already?

Cheers.

**Comment by luisvinicius167** [comment]
Hi @leocavalcante, great! So, I use Grunt to minify. About testing framework, I did not think about it yet. If you can suggest, will be good.

**Comment by leocavalcante** [comment]
@luisvinicius167 would be nice to share your Gruntfile in the repository as well. Also, saw that there is no dependencies declared in you [package.json](http://gruntjs.com/getting-started#package.json). Are you using it by hand on CLI?

For testing, I'm really on to [Mocha](https://mochajs.org/), but I see much more [Jasmine](http://jasmine.github.io/) around the community.

**Comment by luisvinicius167** [comment]
@leocavalcante yes, you are correct. is because I working in other environment, and I forgot to share the package. ;/ I fix it. I will look Jasmine.
